email: lellen@dons.usfca.edu
password: 0Lalala13@@
openaiApiKey: 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
disableAntiLock: false
remote: false
lessthanTenApplicants: false
newestPostingsFirst: true
experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false
jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: false
date:
  all time: false
  month: false
  week: true
  24 hours: true
positions:
  - Machine Learning Engineer
  - Data Scientist
  - AI Engineer
  - Artifical Intelligence Engineer
  # - Computer Vision Engineer
  # - Deep Learning Engineer
  # - NLP Engineer
  # - LLM Engineer
  # - Generative AI Engineer
  # - AI/ML Research Engineer
  # - Data Science Consultant
  # - AI Consultant
  # - Data Analyst
  # - AI Product Developer
  # - Multimodal AI Engineer
  # - Data Engineer (AI focus)
  # - MLOps Engineer
  # - Prompt Engineer
  # - RAG Engineer
  # - AI Content Engineer
  # - ML Engineer - AR
  # - ML - Immersive Experience Engineer
  # - Technical AR/VR Consultant
  # - AI Innovation Specialist
  # - AI Prototyping Engineer
  # - AI Solutions Architect
locations:
- San Francisco
- San Francisco Bay Area
- Bay Area
- San Jose
- San Mateo
- Redwood City
- Palo Alto
- Mountain View
- Sunnyvale
- Cupertino

residentStatus: True
distance: 100
outputFileDirectory: ~/Desktop/MSDS/JS/EasyApplyBot/
companyBlacklist:
- Wayfair
- Jobot
- Crossover

titleBlacklist:
- Founding
- Founder
- Co-Founder
- Cofounder
- Front End
- Frontend
posterBlacklist: []
uploads:
  resume: "Livia Ellen - Resume 2025.pdf"
checkboxes:
  driversLicence: true
  requireVisa: true
  legallyAuthorized: true
  certifiedProfessional: true
  urgentFill: true
  commute: true
  remote: true
  drugTest: true
  assessment: true
  securityClearance: false
  degreeCompleted:
  - Bachelor's Degree
  - Master's Degree
  backgroundCheck: true
universityGpa: 3.6
salaryMinimum: 200000
languages:
  english: Professional
  indonesian: Native
noticePeriod: 4
experience:
  default: 6
personalInfo:
  Pronouns: Ms.
  First Name: Livia
  Last Name: Ellen
  Phone Country Code: United States (+1)
  Mobile Phone Number: '4156380329'
  Street address: 960 Pine St, Apt 24
  City: San Francisco, CA
  State: California
  Zip: '94108'
  Linkedin: https://www.linkedin.com/in/liviaellen/
  Website: https://liviaellen.com/portfolio
  MessageToManager: Hi, I am interested to join your organization. Please have a look
    at my resume. Thank you.
eeo:
  gender: Female
  race: Asian
  veteran: 'No'
  disability: 'No'
  citizenship: F-1 Visa
  clearance: 'No'
evaluateJobFit: false

debug: false

textResume: resume.txt
